# playbook.yml
- name: Configurar servidor web
  hosts: webservers
  become: yes

  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Crear directorio de destino
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copiar index.html al directorio de Apache
      copy:
        src: html/index.html
        dest: /var/www/html/index.html

    - name: Copiar script.js al directorio de Apache
      copy:
        src: html/script.js
        dest: /var/www/html/script.js
